baseURL = "https://michaeltrip.nl"
languageCode = "en-us"
title = "Michaeltrip.nl :: Open Source Consultant"
theme = "hugo-resume"
enableGitInfo = true
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
relativeURLs = true

[params]
    firstName = "Michael"
    lastName = "Trip"
    address = "Apeldoorn, The Netherlands"
    phone = "+31234567890"
    contactNote = "Linux engineer"
    profileImage = "img/myownface.jpg"
    email = "michael@alcatrash.org"
    description = "Experienced SRE / Devops Engineer with a proven knowledge of Cloud native and Kubernetes"
    favicon = "/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true
    showBlog = true
    showQr = true


[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/michaeltrip/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/michaeltrip/"
