name: Build and create docker

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.99.1'
          extended: true

      - name: Build
        run: hugo

      - name: Deploy
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          commit_message: Automated Change
          branch: master
          repository: .


  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: minor

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'

#       - name: get latest git strategy
#         run: |
#           git checkout ${{ steps.bump-semver.outputs.new_version }}

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Login to DockerHub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Build and push
#         uses: docker/build-push-action@v3
#         with:
#           push: true
#           tags: michaeltrip/hugo-michaeltrip.nl:${{ steps.bump-semver.outputs.new_version }},michaeltrip/hugo-michaeltrip.nl:latest
#           platforms: arm64,amd64

#       - name: bump version for application in deployment manifest
#         env:
#           GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
#           TAG: ${{ steps.bump-semver.outputs.new_version }}
#         run: |
#           git clone https://michael:$GITEA_TOKEN@git.alcatrash.net/michael/kubernetes.git
#           cd kubernetes
#           git config user.name "Github actions"
#           git config user.email "github-actions@alcatrash.org"
#           cd argocd/apps/hugo-michaeltrip.nl

#           sed -i "s/\(hugo-michaeltrip.nl:\).*/\1$TAG/g" deployment.yml
#           git add --all
#           git commit -m "updated manifest file. Bumped release to $TAG"
#           git push





# ...
